[package]
name = "static-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pandoc = "0.8"
image = "0.23.14"
regex = "1.5.4"
chrono = "0.4.19"
simple-xml-builder = "1.1.0"
serde_json = "1.0.74"
